#! /bin/bash

# spell-checker: disable

# Create application admin user:

psql -U ${TEST_POSTGRES_USER}  -d ${TEST_POSTGRES_DB}<<- ENDSQL
    CREATE USER "${APP_ADMIN_USER}" WITH SUPERUSER CREATEDB CREATEROLE ENCRYPTED PASSWORD '${APP_ADMIN_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${TEST_POSTGRES_DB} TO "${APP_ADMIN_USER}";
ENDSQL
