services:

  postgresql-db:
    container_name: template-postgresql-db
    restart: no
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file:
      - "./db.env"
      - "./app_db.env"
    build:
      dockerfile: ./dockerfiles/PostgreSQLDockerfile
      context: .
      args:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - PGUSER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - ./database_init:/docker-entrypoint-initdb.d
      - postgresql-db-data:/var/lib/postgresql/docker
    # TODO: Don't expose database port on production environment.
    ports:
      - 5432:5432
    networks:
      - template-net

  postgresql-test-db:
    container_name: template-postgresql-test-db
    # This should be changed to always in production.
    restart: no
    # Set shared memory limit when using docker compose.
    shm_size: 128mb
    env_file:
      - "./test_db.env"
      - "./app_db.env"
    build:
      dockerfile: ./dockerfiles/PostgreSQLTestDockerfile
      context: .
      args:
        - TEST_POSTGRES_DB=${TEST_POSTGRES_DB}
        - TEST_POSTGRES_USER=${TEST_POSTGRES_USER}
        - TEST_POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
        - TEST_PGUSER=${TEST_POSTGRES_USER}
        - TEST_PGPORT=${TEST_PGPORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${TEST_POSTGRES_USER}", "-d", "${TEST_POSTGRES_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    volumes:
      - ./test_database_init:/docker-entrypoint-initdb.d
      - postgresql-test-db-data:/var/lib/postgresql/docker
    # TODO: Don't expose database port on production environment.
    ports:
      - ${TEST_PGPORT}:${TEST_PGPORT}
    networks:
      - template-net

  app:
    container_name: template-app
    depends_on:
      postgresql-db:
        condition: service_healthy
      postgresql-test-db:
        condition: service_healthy
    build:
      dockerfile: ./dockerfiles/AppDockerfile
      context: .
    healthcheck:
      test: ["CMD", "curl", "GET", "http://localhost/health-check"]
      interval: 30s
      timeout: 30s
      retries: 2
      start_period: 10s
    env_file:
      - "./app.env"
      - "./app_db.env"
      - "./test_db.env"
    ports:
      - 1984:1984
      - 80:80
    volumes:
      - "./src:/deploy"
      - "./tests:/deploy/tests"
    networks:
      - template-net

volumes:
  postgresql-db-data:
  postgresql-test-db-data:

networks:
  template-net:
    driver: bridge
