#! /bin/bash

# Create application users:

psql -U ${POSTGRES_USER}  -d ${POSTGRES_DB}<<- ENDSQL
    CREATE USER "${APP_ADMIN_USER}" WITH SUPERUSER CREATEDB CREATEROLE ENCRYPTED PASSWORD '${APP_ADMIN_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO "${APP_ADMIN_USER}";
ENDSQL
